; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [6 x i8] c"Sum: \00"
@.str.6 = private unnamed_addr constant [10 x i8] c"Product: \00"
@.str.7 = private unnamed_addr constant [23 x i8] c"Sum is greater than 25\00"
@.str.8 = private unnamed_addr constant [27 x i8] c"Sum is not greater than 25\00"

@g_x = global i32 0
@g_y = global i32 0
@g_sum = global i32 0

define i32 @main() {
entry:
  %x_addr.0 = alloca i32
  store i32 0, ptr %x_addr.0
  %y_addr.1 = alloca i32
  store i32 0, ptr %y_addr.1
  %sum_addr.2 = alloca i32
  store i32 0, ptr %sum_addr.2
  store i32 10, ptr %x_addr.0
  store i32 20, ptr %y_addr.1
  %load.3 = load i32, ptr %x_addr.0
  %load.4 = load i32, ptr %y_addr.1
  %add.5 = add i32 %load.3, %load.4
  store i32 %add.5, ptr %sum_addr.2
  %load.6 = load i32, ptr %sum_addr.2
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([6 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.6)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %load.7 = load i32, ptr %x_addr.0
  %load.8 = load i32, ptr %y_addr.1
  %mul.9 = mul i32 %load.7, %load.8
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([10 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %mul.9)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %load.10 = load i32, ptr %sum_addr.2
  %cmp.11 = icmp sgt i32 %load.10, 25
  br i1 %cmp.11, label %if_then.0, label %if_else.1
if_then.0:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([23 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_else.1:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([27 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_end.2:
  ret i32 0
}

