; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"one\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"two\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"three\00"
@.str.8 = private unnamed_addr constant [12 x i8] c"Grade: Poor\00"
@.str.9 = private unnamed_addr constant [15 x i8] c"Grade: Average\00"
@.str.10 = private unnamed_addr constant [12 x i8] c"Grade: Good\00"
@.str.11 = private unnamed_addr constant [15 x i8] c"Grade: Unknown\00"

@g_i = global i32 0
@g_grade = global i32 0

define i32 @main() {
entry:
  %i_addr.0 = alloca i32
  store i32 0, ptr %i_addr.0
  %grade_addr.1 = alloca i32
  store i32 0, ptr %grade_addr.1
  %for_counter.2 = alloca i32
  %for_bound.3 = alloca i32
  store i32 1, ptr %for_counter.2
  store i32 3, ptr %for_bound.3
  br label %for_cond.0
for_cond.0:
  %for_cur.4 = load i32, ptr %for_counter.2
  %for_max.5 = load i32, ptr %for_bound.3
  %for_cmp.6 = icmp sle i32 %for_cur.4, %for_max.5
  br i1 %for_cmp.6, label %for_body.1, label %for_end.3
for_body.1:
  %for_visible.7 = load i32, ptr %for_counter.2
  store i32 %for_visible.7, ptr %i_addr.0
  %load.8 = load i32, ptr %i_addr.0
  br label %case_test.5
case_test.5:
  %casecmp.9 = icmp eq i32 %load.8, 1
  br i1 %casecmp.9, label %case_match.6, label %case_next.7
case_match.6:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([4 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.4
case_next.7:
  %casecmp.10 = icmp eq i32 %load.8, 2
  br i1 %casecmp.10, label %case_match.8, label %case_next.9
case_match.8:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([4 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.4
case_next.9:
  %casecmp.11 = icmp eq i32 %load.8, 3
  br i1 %casecmp.11, label %case_match.10, label %case_next.11
case_match.10:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([6 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.4
case_next.11:
  br label %case_end.4
case_end.4:
  br label %for_step.2
for_step.2:
  %for_step_cur.12 = load i32, ptr %for_counter.2
  %for_step_next.13 = add i32 %for_step_cur.12, 1
  store i32 %for_step_next.13, ptr %for_counter.2
  br label %for_cond.0
for_end.3:
  store i32 2, ptr %grade_addr.1
  %load.14 = load i32, ptr %grade_addr.1
  br label %case_test.14
case_test.14:
  %casecmp.15 = icmp eq i32 %load.14, 1
  br i1 %casecmp.15, label %case_match.15, label %case_next.16
case_match.15:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([12 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.12
case_next.16:
  %casecmp.16 = icmp eq i32 %load.14, 2
  br i1 %casecmp.16, label %case_match.17, label %case_next.18
case_match.17:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([15 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.12
case_next.18:
  %casecmp.17 = icmp eq i32 %load.14, 3
  br i1 %casecmp.17, label %case_match.19, label %case_next.20
case_match.19:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([12 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.12
case_next.20:
  br label %case_else.13
case_else.13:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([15 x i8], ptr @.str.11, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %case_end.12
case_end.12:
  ret i32 0
}

