; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [18 x i8] c"Inside Swap: a = \00"
@.str.6 = private unnamed_addr constant [7 x i8] c", b = \00"
@.str.7 = private unnamed_addr constant [13 x i8] c"Max(3, 7) = \00"
@.str.8 = private unnamed_addr constant [14 x i8] c"Max(10, 2) = \00"
@.str.9 = private unnamed_addr constant [13 x i8] c"Min(3, 7) = \00"
@.str.10 = private unnamed_addr constant [21 x i8] c"Clamp(-5, 0, 100) = \00"
@.str.11 = private unnamed_addr constant [21 x i8] c"Clamp(50, 0, 100) = \00"
@.str.12 = private unnamed_addr constant [22 x i8] c"Clamp(200, 0, 100) = \00"
@.str.13 = private unnamed_addr constant [16 x i8] c"Power(2, 10) = \00"
@.str.14 = private unnamed_addr constant [15 x i8] c"Power(3, 4) = \00"
@.str.15 = private unnamed_addr constant [20 x i8] c"SumRange(1, 100) = \00"
@.str.16 = private unnamed_addr constant [17 x i8] c"After Swap, r = \00"
@.str.17 = private unnamed_addr constant [10 x i8] c"4 is even\00"
@.str.18 = private unnamed_addr constant [9 x i8] c"4 is odd\00"
@.str.19 = private unnamed_addr constant [10 x i8] c"7 is even\00"
@.str.20 = private unnamed_addr constant [9 x i8] c"7 is odd\00"

@g_r = global i32 0

define i32 @pas_max(i32 %a, i32 %b) {
entry:
  %addr.0 = alloca i32
  store i32 %a, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %b, ptr %addr.1
  %ret.2 = alloca i32
  store i32 0, ptr %ret.2
  %load.3 = load i32, ptr %addr.0
  %load.4 = load i32, ptr %addr.1
  %cmp.5 = icmp sgt i32 %load.3, %load.4
  br i1 %cmp.5, label %if_then.0, label %if_else.1
if_then.0:
  %load.6 = load i32, ptr %addr.0
  store i32 %load.6, ptr %ret.2
  br label %if_end.2
if_else.1:
  %load.7 = load i32, ptr %addr.1
  store i32 %load.7, ptr %ret.2
  br label %if_end.2
if_end.2:
  %load.8 = load i32, ptr %ret.2
  ret i32 %load.8
}

define i32 @pas_min(i32 %a, i32 %b) {
entry:
  %addr.0 = alloca i32
  store i32 %a, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %b, ptr %addr.1
  %ret.2 = alloca i32
  store i32 0, ptr %ret.2
  %load.3 = load i32, ptr %addr.0
  %load.4 = load i32, ptr %addr.1
  %cmp.5 = icmp slt i32 %load.3, %load.4
  br i1 %cmp.5, label %if_then.0, label %if_else.1
if_then.0:
  %load.6 = load i32, ptr %addr.0
  store i32 %load.6, ptr %ret.2
  br label %if_end.2
if_else.1:
  %load.7 = load i32, ptr %addr.1
  store i32 %load.7, ptr %ret.2
  br label %if_end.2
if_end.2:
  %load.8 = load i32, ptr %ret.2
  ret i32 %load.8
}

define i32 @pas_clamp(i32 %val, i32 %lo, i32 %hi) {
entry:
  %addr.0 = alloca i32
  store i32 %val, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %lo, ptr %addr.1
  %addr.2 = alloca i32
  store i32 %hi, ptr %addr.2
  %ret.3 = alloca i32
  store i32 0, ptr %ret.3
  %load.4 = load i32, ptr %addr.1
  %load.5 = load i32, ptr %addr.0
  %load.6 = load i32, ptr %addr.2
  %call.7 = call i32 @pas_min(i32 %load.5, i32 %load.6)
  %call.8 = call i32 @pas_max(i32 %load.4, i32 %call.7)
  store i32 %call.8, ptr %ret.3
  %load.9 = load i32, ptr %ret.3
  ret i32 %load.9
}

define i32 @pas_power(i32 %base, i32 %exp) {
entry:
  %addr.0 = alloca i32
  store i32 %base, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %exp, ptr %addr.1
  %ret.2 = alloca i32
  store i32 0, ptr %ret.2
  %result_addr.3 = alloca i32
  store i32 0, ptr %result_addr.3
  %i_addr.4 = alloca i32
  store i32 0, ptr %i_addr.4
  store i32 1, ptr %result_addr.3
  %load.5 = load i32, ptr %addr.1
  %for_counter.6 = alloca i32
  %for_bound.7 = alloca i32
  store i32 1, ptr %for_counter.6
  store i32 %load.5, ptr %for_bound.7
  br label %for_cond.0
for_cond.0:
  %for_cur.8 = load i32, ptr %for_counter.6
  %for_max.9 = load i32, ptr %for_bound.7
  %for_cmp.10 = icmp sle i32 %for_cur.8, %for_max.9
  br i1 %for_cmp.10, label %for_body.1, label %for_end.3
for_body.1:
  %for_visible.11 = load i32, ptr %for_counter.6
  store i32 %for_visible.11, ptr %i_addr.4
  %load.12 = load i32, ptr %result_addr.3
  %load.13 = load i32, ptr %addr.0
  %mul.14 = mul i32 %load.12, %load.13
  store i32 %mul.14, ptr %result_addr.3
  br label %for_step.2
for_step.2:
  %for_step_cur.15 = load i32, ptr %for_counter.6
  %for_step_next.16 = add i32 %for_step_cur.15, 1
  store i32 %for_step_next.16, ptr %for_counter.6
  br label %for_cond.0
for_end.3:
  %load.17 = load i32, ptr %result_addr.3
  store i32 %load.17, ptr %ret.2
  %load.18 = load i32, ptr %ret.2
  ret i32 %load.18
}

define i32 @pas_sumrange(i32 %a, i32 %b) {
entry:
  %addr.0 = alloca i32
  store i32 %a, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %b, ptr %addr.1
  %ret.2 = alloca i32
  store i32 0, ptr %ret.2
  %i_addr.3 = alloca i32
  store i32 0, ptr %i_addr.3
  %s_addr.4 = alloca i32
  store i32 0, ptr %s_addr.4
  store i32 0, ptr %s_addr.4
  %load.5 = load i32, ptr %addr.0
  %load.6 = load i32, ptr %addr.1
  %for_counter.7 = alloca i32
  %for_bound.8 = alloca i32
  store i32 %load.5, ptr %for_counter.7
  store i32 %load.6, ptr %for_bound.8
  br label %for_cond.0
for_cond.0:
  %for_cur.9 = load i32, ptr %for_counter.7
  %for_max.10 = load i32, ptr %for_bound.8
  %for_cmp.11 = icmp sle i32 %for_cur.9, %for_max.10
  br i1 %for_cmp.11, label %for_body.1, label %for_end.3
for_body.1:
  %for_visible.12 = load i32, ptr %for_counter.7
  store i32 %for_visible.12, ptr %i_addr.3
  %load.13 = load i32, ptr %s_addr.4
  %load.14 = load i32, ptr %i_addr.3
  %add.15 = add i32 %load.13, %load.14
  store i32 %add.15, ptr %s_addr.4
  br label %for_step.2
for_step.2:
  %for_step_cur.16 = load i32, ptr %for_counter.7
  %for_step_next.17 = add i32 %for_step_cur.16, 1
  store i32 %for_step_next.17, ptr %for_counter.7
  br label %for_cond.0
for_end.3:
  %load.18 = load i32, ptr %s_addr.4
  store i32 %load.18, ptr %ret.2
  %load.19 = load i32, ptr %ret.2
  ret i32 %load.19
}

define void @pas_swap(i32 %a, i32 %b) {
entry:
  %addr.0 = alloca i32
  store i32 %a, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %b, ptr %addr.1
  %temp_addr.2 = alloca i32
  store i32 0, ptr %temp_addr.2
  %load.3 = load i32, ptr %addr.0
  store i32 %load.3, ptr %temp_addr.2
  %load.4 = load i32, ptr %addr.1
  store i32 %load.4, ptr %addr.0
  %load.5 = load i32, ptr %temp_addr.2
  store i32 %load.5, ptr %addr.1
  %load.6 = load i32, ptr %addr.0
  %load.7 = load i32, ptr %addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([18 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.6)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([7 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.7)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  ret void
}

define i1 @pas_iseven(i32 %n) {
entry:
  %addr.0 = alloca i32
  store i32 %n, ptr %addr.0
  %ret.1 = alloca i1
  store i1 false, ptr %ret.1
  %load.2 = load i32, ptr %addr.0
  %mul.3 = srem i32 %load.2, 2
  %cmp.4 = icmp eq i32 %mul.3, 0
  store i1 %cmp.4, ptr %ret.1
  %load.5 = load i1, ptr %ret.1
  ret i1 %load.5
}

define i32 @main() {
entry:
  %r_addr.0 = alloca i32
  store i32 0, ptr %r_addr.0
  %call.1 = call i32 @pas_max(i32 3, i32 7)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.1)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.2 = call i32 @pas_max(i32 10, i32 2)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([14 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.2)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.3 = call i32 @pas_min(i32 3, i32 7)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.3)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %neg.4 = sub i32 0, 5
  %call.5 = call i32 @pas_clamp(i32 %neg.4, i32 0, i32 100)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([21 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.5)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.6 = call i32 @pas_clamp(i32 50, i32 0, i32 100)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([21 x i8], ptr @.str.11, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.6)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.7 = call i32 @pas_clamp(i32 200, i32 0, i32 100)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([22 x i8], ptr @.str.12, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.7)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.8 = call i32 @pas_power(i32 2, i32 10)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([16 x i8], ptr @.str.13, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.8)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.9 = call i32 @pas_power(i32 3, i32 4)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([15 x i8], ptr @.str.14, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.9)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.10 = call i32 @pas_sumrange(i32 1, i32 100)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([20 x i8], ptr @.str.15, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %call.10)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 5, ptr %r_addr.0
  %load.11 = load i32, ptr %r_addr.0
  call void @pas_swap(i32 %load.11, i32 10)
  %load.12 = load i32, ptr %r_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([17 x i8], ptr @.str.16, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.12)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %call.13 = call i1 @pas_iseven(i32 4)
  br i1 %call.13, label %if_then.0, label %if_else.1
if_then.0:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([10 x i8], ptr @.str.17, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_else.1:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([9 x i8], ptr @.str.18, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_end.2:
  %call.14 = call i1 @pas_iseven(i32 7)
  br i1 %call.14, label %if_then.3, label %if_else.4
if_then.3:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([10 x i8], ptr @.str.19, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.5
if_else.4:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([9 x i8], ptr @.str.20, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.5
if_end.5:
  ret i32 0
}

