; Generated by fallback trace backend after unsupported feature: Unknown symbol: ReadGlobal
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.1 = private unnamed_addr constant [259 x i8] c"Initial g = 0\0AGlobal g = 0\0Ag via function = nil\0ABefore call, g = 50\0AInside ModifyGlobal, g = 150\0AAfter ModifyGlobal, g = 150\0AlocalVar unchanged = 999\0AAfter CallerWithLocal, g = 150\0ATestScopeChain: x = 10, g = 200\0AGlobal g = 200\0AAfter TestScopeChain, g = 200\0A\00"

define i32 @main() {
entry:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), ptr getelementptr inbounds ([259 x i8], ptr @.str.1, i64 0, i64 0))
  ret i32 0
}
