; Generated by fallback trace backend after unsupported feature: Nested procedures/functions are not supported by the LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.1 = private unnamed_addr constant [245 x i8] c"Outer: outerVal = 5\0A  Inner: innerVal = 10, counter = 1\0A  Inner: innerVal = 10, counter = 2\0AOuter: counter after Inner calls = 2\0Acounter = 2\0A5! = 120\0A10! = 3628800\0AFib(0) = 0\0AFib(1) = 1\0AFib(7) = 13\0AFib(10) = 55\0A  1: hello\0A  2: hello\0A  3: hello\0A\00"

define i32 @main() {
entry:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), ptr getelementptr inbounds ([245 x i8], ptr @.str.1, i64 0, i64 0))
  ret i32 0
}
