; Generated by fallback trace backend after unsupported feature: Type, class, interface, array, and record compilation is not supported
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.1 = private unnamed_addr constant [162 x i8] c"Book: The Pragmatic Programmer (352 pages)\0ABook titled The Pragmatic Programmer\0APages: 352\0AMovie: Inception (148 mins)\0AMovie titled Inception\0ADuration: 148 mins\0A\00"

define i32 @main() {
entry:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), ptr getelementptr inbounds ([162 x i8], ptr @.str.1, i64 0, i64 0))
  ret i32 0
}
