; Generated by fallback trace backend after unsupported feature: Type, class, interface, array, and record compilation is not supported
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.1 = private unnamed_addr constant [74 x i8] c"Initial: 5\0AAfter 2 increments: 7\0AAfter 1 decrement: 6\0ATCounter destroyed\0A\00"

define i32 @main() {
entry:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), ptr getelementptr inbounds ([74 x i8], ptr @.str.1, i64 0, i64 0))
  ret i32 0
}
