; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [14 x i8] c"Square of 4: \00"
@.str.6 = private unnamed_addr constant [9 x i8] c"7 + 3 = \00"
@.str.7 = private unnamed_addr constant [13 x i8] c"3^2 + 4^2 = \00"

@g_result = global i32 0

define i32 @pas_square(i32 %n) {
entry:
  %addr.0 = alloca i32
  store i32 %n, ptr %addr.0
  %ret.1 = alloca i32
  store i32 0, ptr %ret.1
  %load.2 = load i32, ptr %addr.0
  %load.3 = load i32, ptr %addr.0
  %mul.4 = mul i32 %load.2, %load.3
  store i32 %mul.4, ptr %ret.1
  %load.5 = load i32, ptr %ret.1
  ret i32 %load.5
}

define i32 @pas_add(i32 %a, i32 %b) {
entry:
  %addr.0 = alloca i32
  store i32 %a, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %b, ptr %addr.1
  %ret.2 = alloca i32
  store i32 0, ptr %ret.2
  %load.3 = load i32, ptr %addr.0
  %load.4 = load i32, ptr %addr.1
  %add.5 = add i32 %load.3, %load.4
  store i32 %add.5, ptr %ret.2
  %load.6 = load i32, ptr %ret.2
  ret i32 %load.6
}

define void @pas_printresult(ptr %label_, i32 %value) {
entry:
  %addr.0 = alloca ptr
  store ptr %label_, ptr %addr.0
  %addr.1 = alloca i32
  store i32 %value, ptr %addr.1
  %load.2 = load ptr, ptr %addr.0
  %load.3 = load i32, ptr %addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr %load.2)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.3)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  ret void
}

define i32 @main() {
entry:
  %result_addr.0 = alloca i32
  store i32 0, ptr %result_addr.0
  %call.1 = call i32 @pas_square(i32 4)
  store i32 %call.1, ptr %result_addr.0
  %load.2 = load i32, ptr %result_addr.0
  call void @pas_printresult(ptr getelementptr inbounds ([14 x i8], ptr @.str.5, i64 0, i64 0), i32 %load.2)
  %call.3 = call i32 @pas_add(i32 7, i32 3)
  store i32 %call.3, ptr %result_addr.0
  %load.4 = load i32, ptr %result_addr.0
  call void @pas_printresult(ptr getelementptr inbounds ([9 x i8], ptr @.str.6, i64 0, i64 0), i32 %load.4)
  %call.5 = call i32 @pas_square(i32 3)
  %call.6 = call i32 @pas_square(i32 4)
  %call.7 = call i32 @pas_add(i32 %call.5, i32 %call.6)
  store i32 %call.7, ptr %result_addr.0
  %load.8 = load i32, ptr %result_addr.0
  call void @pas_printresult(ptr getelementptr inbounds ([13 x i8], ptr @.str.7, i64 0, i64 0), i32 %load.8)
  ret i32 0
}

