; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [19 x i8] c"Odd numbers 1..10:\00"
@.str.6 = private unnamed_addr constant [2 x i8] c" \00"
@.str.7 = private unnamed_addr constant [1 x i8] c"\00"
@.str.8 = private unnamed_addr constant [27 x i8] c"Non-multiples of 3, 1..12:\00"
@.str.9 = private unnamed_addr constant [15 x i8] c"Repeat skip 3:\00"
@.str.10 = private unnamed_addr constant [23 x i8] c"Skip even, break at 7:\00"

@g_i = global i32 0
@g_total = global i32 0

define i32 @main() {
entry:
  %i_addr.0 = alloca i32
  store i32 0, ptr %i_addr.0
  %total_addr.1 = alloca i32
  store i32 0, ptr %total_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([19 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %for_counter.2 = alloca i32
  %for_bound.3 = alloca i32
  store i32 1, ptr %for_counter.2
  store i32 10, ptr %for_bound.3
  br label %for_cond.0
for_cond.0:
  %for_cur.4 = load i32, ptr %for_counter.2
  %for_max.5 = load i32, ptr %for_bound.3
  %for_cmp.6 = icmp sle i32 %for_cur.4, %for_max.5
  br i1 %for_cmp.6, label %for_body.1, label %for_end.3
for_body.1:
  %for_visible.7 = load i32, ptr %for_counter.2
  store i32 %for_visible.7, ptr %i_addr.0
  %load.8 = load i32, ptr %i_addr.0
  %mul.9 = srem i32 %load.8, 2
  %cmp.10 = icmp eq i32 %mul.9, 0
  br i1 %cmp.10, label %if_then.4, label %if_end.5
if_then.4:
  br label %for_step.2
if_end.5:
  %load.11 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.11)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %for_step.2
for_step.2:
  %for_step_cur.12 = load i32, ptr %for_counter.2
  %for_step_next.13 = add i32 %for_step_cur.12, 1
  store i32 %for_step_next.13, ptr %for_counter.2
  br label %for_cond.0
for_end.3:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([27 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %i_addr.0
  br label %while_cond.6
while_cond.6:
  %load.14 = load i32, ptr %i_addr.0
  %cmp.15 = icmp slt i32 %load.14, 12
  br i1 %cmp.15, label %while_body.7, label %while_end.8
while_body.7:
  %load.16 = load i32, ptr %i_addr.0
  %add.17 = add i32 %load.16, 1
  store i32 %add.17, ptr %i_addr.0
  %load.18 = load i32, ptr %i_addr.0
  %mul.19 = srem i32 %load.18, 3
  %cmp.20 = icmp eq i32 %mul.19, 0
  br i1 %cmp.20, label %if_then.9, label %if_end.10
if_then.9:
  br label %while_cond.6
if_end.10:
  %load.21 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.21)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %while_cond.6
while_end.8:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([15 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %i_addr.0
  br label %repeat_body.11
repeat_body.11:
  %load.22 = load i32, ptr %i_addr.0
  %add.23 = add i32 %load.22, 1
  store i32 %add.23, ptr %i_addr.0
  %load.24 = load i32, ptr %i_addr.0
  %cmp.25 = icmp eq i32 %load.24, 3
  br i1 %cmp.25, label %if_then.14, label %if_end.15
if_then.14:
  br label %repeat_cond.12
if_end.15:
  %load.26 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.26)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %repeat_cond.12
repeat_cond.12:
  %load.27 = load i32, ptr %i_addr.0
  %cmp.28 = icmp eq i32 %load.27, 5
  br i1 %cmp.28, label %repeat_end.13, label %repeat_body.11
repeat_end.13:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([23 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %for_counter.29 = alloca i32
  %for_bound.30 = alloca i32
  store i32 1, ptr %for_counter.29
  store i32 10, ptr %for_bound.30
  br label %for_cond.16
for_cond.16:
  %for_cur.31 = load i32, ptr %for_counter.29
  %for_max.32 = load i32, ptr %for_bound.30
  %for_cmp.33 = icmp sle i32 %for_cur.31, %for_max.32
  br i1 %for_cmp.33, label %for_body.17, label %for_end.19
for_body.17:
  %for_visible.34 = load i32, ptr %for_counter.29
  store i32 %for_visible.34, ptr %i_addr.0
  %load.35 = load i32, ptr %i_addr.0
  %cmp.36 = icmp eq i32 %load.35, 7
  br i1 %cmp.36, label %if_then.20, label %if_end.21
if_then.20:
  br label %for_end.19
if_end.21:
  %load.37 = load i32, ptr %i_addr.0
  %mul.38 = srem i32 %load.37, 2
  %cmp.39 = icmp eq i32 %mul.38, 0
  br i1 %cmp.39, label %if_then.22, label %if_end.23
if_then.22:
  br label %for_step.18
if_end.23:
  %load.40 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.40)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %for_step.18
for_step.18:
  %for_step_cur.41 = load i32, ptr %for_counter.29
  %for_step_next.42 = add i32 %for_step_cur.41, 1
  store i32 %for_step_next.42, ptr %for_counter.29
  br label %for_cond.16
for_end.19:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  ret i32 0
}

