; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [11 x i8] c"while i = \00"
@.str.6 = private unnamed_addr constant [21 x i8] c"Exited while at i = \00"
@.str.7 = private unnamed_addr constant [9 x i8] c"for i = \00"
@.str.8 = private unnamed_addr constant [19 x i8] c"Exited for at i = \00"
@.str.9 = private unnamed_addr constant [12 x i8] c"downto i = \00"
@.str.10 = private unnamed_addr constant [22 x i8] c"Exited downto at i = \00"
@.str.11 = private unnamed_addr constant [11 x i8] c"outer i = \00"
@.str.12 = private unnamed_addr constant [17 x i8] c"  inner total = \00"

@g_i = global i32 0
@g_total = global i32 0

define i32 @main() {
entry:
  %i_addr.0 = alloca i32
  store i32 0, ptr %i_addr.0
  %total_addr.1 = alloca i32
  store i32 0, ptr %total_addr.1
  store i32 1, ptr %i_addr.0
  br label %while_cond.0
while_cond.0:
  %load.2 = load i32, ptr %i_addr.0
  %cmp.3 = icmp sle i32 %load.2, 10
  br i1 %cmp.3, label %while_body.1, label %while_end.2
while_body.1:
  %load.4 = load i32, ptr %i_addr.0
  %cmp.5 = icmp eq i32 %load.4, 5
  br i1 %cmp.5, label %if_then.3, label %if_end.4
if_then.3:
  br label %while_end.2
if_end.4:
  %load.6 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([11 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.6)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %load.7 = load i32, ptr %i_addr.0
  %add.8 = add i32 %load.7, 1
  store i32 %add.8, ptr %i_addr.0
  br label %while_cond.0
while_end.2:
  %load.9 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([21 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.9)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %for_counter.10 = alloca i32
  %for_bound.11 = alloca i32
  store i32 1, ptr %for_counter.10
  store i32 10, ptr %for_bound.11
  br label %for_cond.5
for_cond.5:
  %for_cur.12 = load i32, ptr %for_counter.10
  %for_max.13 = load i32, ptr %for_bound.11
  %for_cmp.14 = icmp sle i32 %for_cur.12, %for_max.13
  br i1 %for_cmp.14, label %for_body.6, label %for_end.8
for_body.6:
  %for_visible.15 = load i32, ptr %for_counter.10
  store i32 %for_visible.15, ptr %i_addr.0
  %load.16 = load i32, ptr %i_addr.0
  %cmp.17 = icmp eq i32 %load.16, 3
  br i1 %cmp.17, label %if_then.9, label %if_end.10
if_then.9:
  br label %for_end.8
if_end.10:
  %load.18 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([9 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.18)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %for_step.7
for_step.7:
  %for_step_cur.19 = load i32, ptr %for_counter.10
  %for_step_next.20 = add i32 %for_step_cur.19, 1
  store i32 %for_step_next.20, ptr %for_counter.10
  br label %for_cond.5
for_end.8:
  %load.21 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([19 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.21)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %for_counter.22 = alloca i32
  %for_bound.23 = alloca i32
  store i32 10, ptr %for_counter.22
  store i32 1, ptr %for_bound.23
  br label %for_cond.11
for_cond.11:
  %for_cur.24 = load i32, ptr %for_counter.22
  %for_max.25 = load i32, ptr %for_bound.23
  %for_cmp.26 = icmp sge i32 %for_cur.24, %for_max.25
  br i1 %for_cmp.26, label %for_body.12, label %for_end.14
for_body.12:
  %for_visible.27 = load i32, ptr %for_counter.22
  store i32 %for_visible.27, ptr %i_addr.0
  %load.28 = load i32, ptr %i_addr.0
  %cmp.29 = icmp eq i32 %load.28, 7
  br i1 %cmp.29, label %if_then.15, label %if_end.16
if_then.15:
  br label %for_end.14
if_end.16:
  %load.30 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([12 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.30)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %for_step.13
for_step.13:
  %for_step_cur.31 = load i32, ptr %for_counter.22
  %for_step_next.32 = sub i32 %for_step_cur.31, 1
  store i32 %for_step_next.32, ptr %for_counter.22
  br label %for_cond.11
for_end.14:
  %load.33 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([22 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.33)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %total_addr.1
  %for_counter.34 = alloca i32
  %for_bound.35 = alloca i32
  store i32 1, ptr %for_counter.34
  store i32 3, ptr %for_bound.35
  br label %for_cond.17
for_cond.17:
  %for_cur.36 = load i32, ptr %for_counter.34
  %for_max.37 = load i32, ptr %for_bound.35
  %for_cmp.38 = icmp sle i32 %for_cur.36, %for_max.37
  br i1 %for_cmp.38, label %for_body.18, label %for_end.20
for_body.18:
  %for_visible.39 = load i32, ptr %for_counter.34
  store i32 %for_visible.39, ptr %i_addr.0
  %load.40 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([11 x i8], ptr @.str.11, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.40)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %total_addr.1
  br label %while_cond.21
while_cond.21:
  %load.41 = load i32, ptr %total_addr.1
  %cmp.42 = icmp slt i32 %load.41, 100
  br i1 %cmp.42, label %while_body.22, label %while_end.23
while_body.22:
  %load.43 = load i32, ptr %total_addr.1
  %add.44 = add i32 %load.43, 10
  store i32 %add.44, ptr %total_addr.1
  %load.45 = load i32, ptr %total_addr.1
  %cmp.46 = icmp eq i32 %load.45, 30
  br i1 %cmp.46, label %if_then.24, label %if_end.25
if_then.24:
  br label %while_end.23
if_end.25:
  br label %while_cond.21
while_end.23:
  %load.47 = load i32, ptr %total_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([17 x i8], ptr @.str.12, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.47)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %for_step.19
for_step.19:
  %for_step_cur.48 = load i32, ptr %for_counter.34
  %for_step_next.49 = add i32 %for_step_cur.48, 1
  store i32 %for_step_next.49, ptr %for_counter.34
  br label %for_cond.17
for_end.20:
  ret i32 0
}

