; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [15 x i8] c"v = C*(A+B) = \00"
@.str.6 = private unnamed_addr constant [13 x i8] c"w = A+B+C = \00"
@.str.7 = private unnamed_addr constant [21 x i8] c"x = 5 + C*Product = \00"
@.str.8 = private unnamed_addr constant [13 x i8] c"100 div 4 = \00"
@.str.9 = private unnamed_addr constant [13 x i8] c"100 mod 7 = \00"
@.str.10 = private unnamed_addr constant [13 x i8] c"3*3 + 4*4 = \00"
@.str.11 = private unnamed_addr constant [6 x i8] c"A > B\00"
@.str.12 = private unnamed_addr constant [7 x i8] c"A <= B\00"
@.str.13 = private unnamed_addr constant [19 x i8] c"A + B = 21 is true\00"
@.str.14 = private unnamed_addr constant [2 x i8] c" \00"
@.str.15 = private unnamed_addr constant [1 x i8] c"\00"

@g_v = global i32 0
@g_w = global i32 0
@g_x = global i32 0

define i32 @main() {
entry:
  %v_addr.0 = alloca i32
  store i32 0, ptr %v_addr.0
  %w_addr.1 = alloca i32
  store i32 0, ptr %w_addr.1
  %x_addr.2 = alloca i32
  store i32 0, ptr %x_addr.2
  %add.3 = add i32 10, 11
  %mul.4 = mul i32 2, %add.3
  store i32 %mul.4, ptr %v_addr.0
  %load.5 = load i32, ptr %v_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([15 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.5)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %add.6 = add i32 11, 2
  %add.7 = add i32 10, %add.6
  store i32 %add.7, ptr %w_addr.1
  %load.8 = load i32, ptr %w_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.8)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 5, ptr %x_addr.2
  %load.9 = load i32, ptr %x_addr.2
  %mul.10 = mul i32 2, 6
  %add.11 = add i32 %load.9, %mul.10
  store i32 %add.11, ptr %x_addr.2
  %load.12 = load i32, ptr %x_addr.2
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([21 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.12)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %mul.13 = sdiv i32 100, 4
  store i32 %mul.13, ptr %v_addr.0
  %load.14 = load i32, ptr %v_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.14)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %mul.15 = srem i32 100, 7
  store i32 %mul.15, ptr %v_addr.0
  %load.16 = load i32, ptr %v_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.16)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %mul.17 = mul i32 3, 3
  %mul.18 = mul i32 4, 4
  %add.19 = add i32 %mul.17, %mul.18
  store i32 %add.19, ptr %v_addr.0
  %load.20 = load i32, ptr %v_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([13 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.20)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %cmp.21 = icmp sgt i32 10, 11
  br i1 %cmp.21, label %if_then.0, label %if_else.1
if_then.0:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([6 x i8], ptr @.str.11, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_else.1:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([7 x i8], ptr @.str.12, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.2
if_end.2:
  %add.22 = add i32 10, 11
  %cmp.23 = icmp eq i32 %add.22, 21
  br i1 %cmp.23, label %if_then.3, label %if_end.4
if_then.3:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([19 x i8], ptr @.str.13, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.4
if_end.4:
  %add.24 = add i32 11, 5
  %add.25 = sub i32 10, %add.24
  %for_counter.26 = alloca i32
  %for_bound.27 = alloca i32
  store i32 1, ptr %for_counter.26
  store i32 %add.25, ptr %for_bound.27
  br label %for_cond.5
for_cond.5:
  %for_cur.28 = load i32, ptr %for_counter.26
  %for_max.29 = load i32, ptr %for_bound.27
  %for_cmp.30 = icmp sle i32 %for_cur.28, %for_max.29
  br i1 %for_cmp.30, label %for_body.6, label %for_end.8
for_body.6:
  %for_visible.31 = load i32, ptr %for_counter.26
  store i32 %for_visible.31, ptr %v_addr.0
  %load.32 = load i32, ptr %v_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.32)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.14, i64 0, i64 0))
  br label %for_step.7
for_step.7:
  %for_step_cur.33 = load i32, ptr %for_counter.26
  %for_step_next.34 = add i32 %for_step_cur.33, 1
  store i32 %for_step_next.34, ptr %for_counter.26
  br label %for_cond.5
for_end.8:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.15, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  ret i32 0
}

