; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [5 x i8] c"i = \00"
@.str.6 = private unnamed_addr constant [19 x i8] c", running total = \00"
@.str.7 = private unnamed_addr constant [12 x i8] c"Sum 1..5 = \00"
@.str.8 = private unnamed_addr constant [8 x i8] c"while: \00"
@.str.9 = private unnamed_addr constant [9 x i8] c"repeat: \00"

@g_i = global i32 0
@g_total = global i32 0

define i32 @main() {
entry:
  %i_addr.0 = alloca i32
  store i32 0, ptr %i_addr.0
  %total_addr.1 = alloca i32
  store i32 0, ptr %total_addr.1
  store i32 0, ptr %total_addr.1
  %for_counter.2 = alloca i32
  %for_bound.3 = alloca i32
  store i32 1, ptr %for_counter.2
  store i32 5, ptr %for_bound.3
  br label %for_cond.0
for_cond.0:
  %for_cur.4 = load i32, ptr %for_counter.2
  %for_max.5 = load i32, ptr %for_bound.3
  %for_cmp.6 = icmp sle i32 %for_cur.4, %for_max.5
  br i1 %for_cmp.6, label %for_body.1, label %for_end.3
for_body.1:
  %for_visible.7 = load i32, ptr %for_counter.2
  store i32 %for_visible.7, ptr %i_addr.0
  %load.8 = load i32, ptr %total_addr.1
  %load.9 = load i32, ptr %i_addr.0
  %add.10 = add i32 %load.8, %load.9
  store i32 %add.10, ptr %total_addr.1
  %load.11 = load i32, ptr %i_addr.0
  %load.12 = load i32, ptr %total_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([5 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.11)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([19 x i8], ptr @.str.6, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.12)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %for_step.2
for_step.2:
  %for_step_cur.13 = load i32, ptr %for_counter.2
  %for_step_next.14 = add i32 %for_step_cur.13, 1
  store i32 %for_step_next.14, ptr %for_counter.2
  br label %for_cond.0
for_end.3:
  %load.15 = load i32, ptr %total_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([12 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.15)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 1, ptr %i_addr.0
  br label %while_cond.4
while_cond.4:
  %load.16 = load i32, ptr %i_addr.0
  %cmp.17 = icmp sle i32 %load.16, 3
  br i1 %cmp.17, label %while_body.5, label %while_end.6
while_body.5:
  %load.18 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([8 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.18)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %load.19 = load i32, ptr %i_addr.0
  %add.20 = add i32 %load.19, 1
  store i32 %add.20, ptr %i_addr.0
  br label %while_cond.4
while_end.6:
  store i32 0, ptr %i_addr.0
  br label %repeat_body.7
repeat_body.7:
  %load.21 = load i32, ptr %i_addr.0
  %add.22 = add i32 %load.21, 1
  store i32 %add.22, ptr %i_addr.0
  %load.23 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([9 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.23)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %repeat_cond.8
repeat_cond.8:
  %load.24 = load i32, ptr %i_addr.0
  %cmp.25 = icmp eq i32 %load.24, 3
  br i1 %cmp.25, label %repeat_end.9, label %repeat_body.7
repeat_end.9:
  ret i32 0
}

