; Generated by the Delphi LLVM compiler backend
declare i32 @printf(ptr noundef, ...)

@.str.0 = private unnamed_addr constant [3 x i8] c"%d\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"false\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.5 = private unnamed_addr constant [24 x i8] c"Repeat with break at 4:\00"
@.str.6 = private unnamed_addr constant [2 x i8] c" \00"
@.str.7 = private unnamed_addr constant [1 x i8] c"\00"
@.str.8 = private unnamed_addr constant [16 x i8] c"Stopped at i = \00"
@.str.9 = private unnamed_addr constant [35 x i8] c"Nested loops, inner breaks at j=3:\00"
@.str.10 = private unnamed_addr constant [3 x i8] c"i=\00"
@.str.11 = private unnamed_addr constant [3 x i8] c": \00"
@.str.12 = private unnamed_addr constant [30 x i8] c"Outer continue + inner break:\00"
@.str.13 = private unnamed_addr constant [22 x i8] c", inner stopped at j=\00"
@.str.14 = private unnamed_addr constant [25 x i8] c"First i where i*i > 50: \00"
@.str.15 = private unnamed_addr constant [10 x i8] c"Not found\00"

@g_i = global i32 0
@g_j = global i32 0
@g_found = global i1 false

define i32 @main() {
entry:
  %i_addr.0 = alloca i32
  store i32 0, ptr %i_addr.0
  %j_addr.1 = alloca i32
  store i32 0, ptr %j_addr.1
  %found_addr.2 = alloca i1
  store i1 false, ptr %found_addr.2
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([24 x i8], ptr @.str.5, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %i_addr.0
  br label %repeat_body.0
repeat_body.0:
  %load.3 = load i32, ptr %i_addr.0
  %add.4 = add i32 %load.3, 1
  store i32 %add.4, ptr %i_addr.0
  %load.5 = load i32, ptr %i_addr.0
  %cmp.6 = icmp eq i32 %load.5, 4
  br i1 %cmp.6, label %if_then.3, label %if_end.4
if_then.3:
  br label %repeat_end.2
if_end.4:
  %load.7 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.7)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %repeat_cond.1
repeat_cond.1:
  %load.8 = load i32, ptr %i_addr.0
  %cmp.9 = icmp eq i32 %load.8, 10
  br i1 %cmp.9, label %repeat_end.2, label %repeat_body.0
repeat_end.2:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %load.10 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([16 x i8], ptr @.str.8, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.10)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([35 x i8], ptr @.str.9, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  %for_counter.11 = alloca i32
  %for_bound.12 = alloca i32
  store i32 1, ptr %for_counter.11
  store i32 4, ptr %for_bound.12
  br label %for_cond.5
for_cond.5:
  %for_cur.13 = load i32, ptr %for_counter.11
  %for_max.14 = load i32, ptr %for_bound.12
  %for_cmp.15 = icmp sle i32 %for_cur.13, %for_max.14
  br i1 %for_cmp.15, label %for_body.6, label %for_end.8
for_body.6:
  %for_visible.16 = load i32, ptr %for_counter.11
  store i32 %for_visible.16, ptr %i_addr.0
  %load.17 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([3 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.17)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([3 x i8], ptr @.str.11, i64 0, i64 0))
  %for_counter.18 = alloca i32
  %for_bound.19 = alloca i32
  store i32 1, ptr %for_counter.18
  store i32 5, ptr %for_bound.19
  br label %for_cond.9
for_cond.9:
  %for_cur.20 = load i32, ptr %for_counter.18
  %for_max.21 = load i32, ptr %for_bound.19
  %for_cmp.22 = icmp sle i32 %for_cur.20, %for_max.21
  br i1 %for_cmp.22, label %for_body.10, label %for_end.12
for_body.10:
  %for_visible.23 = load i32, ptr %for_counter.18
  store i32 %for_visible.23, ptr %j_addr.1
  %load.24 = load i32, ptr %j_addr.1
  %cmp.25 = icmp eq i32 %load.24, 3
  br i1 %cmp.25, label %if_then.13, label %if_end.14
if_then.13:
  br label %for_end.12
if_end.14:
  %load.26 = load i32, ptr %j_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.26)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.6, i64 0, i64 0))
  br label %for_step.11
for_step.11:
  %for_step_cur.27 = load i32, ptr %for_counter.18
  %for_step_next.28 = add i32 %for_step_cur.27, 1
  store i32 %for_step_next.28, ptr %for_counter.18
  br label %for_cond.9
for_end.12:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([1 x i8], ptr @.str.7, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %for_step.7
for_step.7:
  %for_step_cur.29 = load i32, ptr %for_counter.11
  %for_step_next.30 = add i32 %for_step_cur.29, 1
  store i32 %for_step_next.30, ptr %for_counter.11
  br label %for_cond.5
for_end.8:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([30 x i8], ptr @.str.12, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  store i32 0, ptr %i_addr.0
  br label %while_cond.15
while_cond.15:
  %load.31 = load i32, ptr %i_addr.0
  %cmp.32 = icmp slt i32 %load.31, 6
  br i1 %cmp.32, label %while_body.16, label %while_end.17
while_body.16:
  %load.33 = load i32, ptr %i_addr.0
  %add.34 = add i32 %load.33, 1
  store i32 %add.34, ptr %i_addr.0
  %load.35 = load i32, ptr %i_addr.0
  %cmp.36 = icmp eq i32 %load.35, 3
  br i1 %cmp.36, label %if_then.18, label %if_end.19
if_then.18:
  br label %while_cond.15
if_end.19:
  store i32 0, ptr %j_addr.1
  br label %while_cond.20
while_cond.20:
  %load.37 = load i32, ptr %j_addr.1
  %cmp.38 = icmp slt i32 %load.37, 10
  br i1 %cmp.38, label %while_body.21, label %while_end.22
while_body.21:
  %load.39 = load i32, ptr %j_addr.1
  %add.40 = add i32 %load.39, 1
  store i32 %add.40, ptr %j_addr.1
  %load.41 = load i32, ptr %j_addr.1
  %cmp.42 = icmp sgt i32 %load.41, 2
  br i1 %cmp.42, label %if_then.23, label %if_end.24
if_then.23:
  br label %while_end.22
if_end.24:
  br label %while_cond.20
while_end.22:
  %load.43 = load i32, ptr %i_addr.0
  %load.44 = load i32, ptr %j_addr.1
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([3 x i8], ptr @.str.10, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.43)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([22 x i8], ptr @.str.13, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.44)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %while_cond.15
while_end.17:
  store i1 false, ptr %found_addr.2
  %for_counter.45 = alloca i32
  %for_bound.46 = alloca i32
  store i32 1, ptr %for_counter.45
  store i32 100, ptr %for_bound.46
  br label %for_cond.25
for_cond.25:
  %for_cur.47 = load i32, ptr %for_counter.45
  %for_max.48 = load i32, ptr %for_bound.46
  %for_cmp.49 = icmp sle i32 %for_cur.47, %for_max.48
  br i1 %for_cmp.49, label %for_body.26, label %for_end.28
for_body.26:
  %for_visible.50 = load i32, ptr %for_counter.45
  store i32 %for_visible.50, ptr %i_addr.0
  %load.51 = load i32, ptr %i_addr.0
  %load.52 = load i32, ptr %i_addr.0
  %mul.53 = mul i32 %load.51, %load.52
  %cmp.54 = icmp sgt i32 %mul.53, 50
  br i1 %cmp.54, label %if_then.29, label %if_end.30
if_then.29:
  store i1 true, ptr %found_addr.2
  br label %for_end.28
if_end.30:
  br label %for_step.27
for_step.27:
  %for_step_cur.55 = load i32, ptr %for_counter.45
  %for_step_next.56 = add i32 %for_step_cur.55, 1
  store i32 %for_step_next.56, ptr %for_counter.45
  br label %for_cond.25
for_end.28:
  %load.57 = load i1, ptr %found_addr.2
  br i1 %load.57, label %if_then.31, label %if_else.32
if_then.31:
  %load.58 = load i32, ptr %i_addr.0
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([25 x i8], ptr @.str.14, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.0, i64 0, i64 0), i32 %load.58)
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.33
if_else.32:
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([10 x i8], ptr @.str.15, i64 0, i64 0))
  call i32 (ptr, ...) @printf(ptr getelementptr inbounds ([3 x i8], ptr @.str.1, i64 0, i64 0), ptr getelementptr inbounds ([2 x i8], ptr @.str.4, i64 0, i64 0))
  br label %if_end.33
if_end.33:
  ret i32 0
}

